python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-11-05.xlsx --instance=dragon88
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-05.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-11-06.xlsx --instance=dragon88
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-06.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-11-07.xlsx --instance=dragon88
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-07.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-11-08.xlsx --instance=dragon88
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-08.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-09.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-10.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-11.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-11-12.xlsx --instance=dragon88
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-12.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-11-13.xlsx --instance=dragon88
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-13.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-11-14.xlsx --instance=dragon88
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-14.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-11-15.xlsx --instance=dragon88
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-15.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-16.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-17.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-18.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-19.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-20.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-21.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-22.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-11-23.xlsx --instance=dragon
