python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-09-19.xlsx --instance=dragon88
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-19.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-09-20.xlsx --instance=dragon88
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-20.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-09-21.xlsx --instance=dragon88
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-21.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-22.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-23.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-24.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-25.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-26.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-27.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-28.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-29.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-09-30.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-10-01.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-10-02.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_DragonShared/2023-10-03.xlsx --instance=dragon
python migration_seeder.py --file=/home/christopher/Downloads/Dataset_88Shared/2023-10-03.xlsx --instance=dragon88
